Side Panel Communication [ED-9579]
mark-elementor/elementor pull request #4
Opened 2023-03-07 15:32 UTC by ZeyadMahagna

2023-03-08 07:22 UTC, ManorHazazE requested changes

2023-03-08 13:30 UTC, ManorHazazE requested changes

2023-03-08 13:30 UTC, ManorHazazE commented on assets/dev/js/editor/controls/popover-toggle.js
> +		$e.run( 'panel/global/toggle-picker', { controlView: this } );
Should be removed?

2023-03-08 13:30 UTC, ManorHazazE commented on assets/dev/js/editor/controls/popover-toggle.js
> +		$e.run( 'panel/control-toggled', { controlView: this } );
I thought you going to split the color and the popover toggles into 2 separate commands no?

2023-03-08 13:30 UTC, ManorHazazE commented on assets/dev/js/editor/editor-base.js
> +					$element.trigger( 'onHide' );
```suggestion
					$element.trigger( 'hide' );
```

2023-03-08 13:30 UTC, ManorHazazE commented on assets/dev/js/editor/controls/popover-toggle.js
> +		$popover.on( 'onHide', () => this.onPopoverHide() );
```suggestion
		$popover.on( 'hide', () => this.onPopoverHide() );
```

2023-03-08 13:49 UTC, ZeyadMahagna commented on assets/dev/js/editor/controls/popover-toggle.js
> +		$e.run( 'panel/global/toggle-picker', { controlView: this } );
Why? If we can let's go through the toggle command rather than directly toggling

2023-03-09 15:20 UTC, Nevoss requested changes
Please consult with @matipojo there are some issues here that he can help with in terms of the general idea of the web cli system

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/controls/commands/color-toggled.js
> +export class ColorToggled extends ControlToggled {
Maybe remove the class? seems a little bit weird to extend a class without doing anything.

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/controls/commands/popover-toggle-toggled.js
> +export class PopoverToggleToggled extends ControlToggled {
Same as above

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/controls/commands/toggle-control.js
> +		controlView.toggle();
Please validate the the control have `toggle` method

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/controls/commands/toggle-control.js
> +		}
Is it required?

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/controls/repeater-row.js
> +	},
How this is related to the PR?

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/controls/repeater.js
> +	},
How this is related to the PR?

2023-03-09 15:20 UTC, Nevoss commented on assets/dev/js/editor/editor-base.js
> +			} );
How this is related to the PR?

2023-03-12 08:37 UTC, ZeyadMahagna commented on assets/dev/js/editor/controls/repeater-row.js
> +	},
The controlView we can get directly with:
`elementor.getPanelView().getCurrentPageView().content.currentView.getControlViewByName( NAME )`
was a repeater control and since we actually need the color control sitting inside the repeater (which sits inside the repeater-row contorl) in both the colors and fonts cases, these are methods I added to the repeater and repeater-row controls to get a controlView from its children by ID or NAME
You can see how I use them in the `getControlView` method in the ToggleControl command

2023-03-12 08:44 UTC, ZeyadMahagna commented on assets/dev/js/editor/editor-base.js
> +			} );
So we needed to emit an event when the popover is hidden (but only when it was actually visible before since this hide originally ran for all elements with the specified class in the DOM regardless of whether they were visible or not) hence this refactor. no this emitted `hide` is listen to in the popover-toggle control and fires the toggled command in its callback

2023-03-12 15:25 UTC, matipojo requested changes

2023-03-12 15:25 UTC, matipojo commented on assets/dev/js/editor/controls/color.js
> +			onPickerHide: () => this.runToggledCommand(),
The command pattern works in the opposite way, you should be able to run it from the console, and it will apply what you need.

In this case, it's a UI with a persistent state (open/close) so it should be a part of the routing system, for example: 
```
$e.route( 'panel/editor/style', {  controlPath: <control-path> } );
```

2023-03-14 13:56 UTC, matipojo requested changes

2023-03-14 13:56 UTC, matipojo commented on modules/web-cli/assets/js/core/commands.js
> +	}
It shouldn't be changed externally

2023-03-14 13:56 UTC, matipojo commented on assets/dev/js/editor/controls/color.js
> +	}
I didn't understand what it does.

2023-03-16 07:55 UTC, merged